kind: Service 
apiVersion: v1 
metadata:
  name: lti-marketplace-service 
spec:

  type: NodePort


  selector:
    app: lti-marketplace 

  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - nodePort: 30164
      port: 8090 
      targetPort: 8089